server:
  port: 9095
spring:
  application:
    name: e-commerce-assesment
  datasource:
    name: assesment
    url: jdbc:mysql://localhost:3306/ecommerce_test
    username: def_shiv
    password: def_shiv
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect